import type { Metadata } from "next";
import { Providers } from "@/utils/chakra-ui/providers";
import { inter } from "@/assets/fonts/fonts";
import { genjyuuRegular } from "@/assets/fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.className} ${genjyuuRegular.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
